services:
  nginx:
    image: nginx:1-alpine
    volumes:
      - ./:/var/www/html
      - ./build/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    image: php:8.4-fpm-alpine
    volumes:
      - ./:/var/www/html