services:
  nginx:
    image: nginx:1-alpine
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-proxy-manager
  php-fpm:
    image: php:8.4-fpm-alpine
    volumes:
      - ./:/var/www/html
    networks:
      - nginx-proxy-manager
networks:
  nginx-proxy-manager:
      external: true
      name: nginx-proxy-manager_default